### ISSUE TITLE
how do you run the package

### ISSUE THREAD

**Issue by monbro** [aumel/meteor-security-authorization#2]
I am on node v5.6.0 currently and meteor 1.2.1 but I am getting:

`class MySecurityVoter extends AbstractVoter {
W20160215-13:40:23.444(1)? (STDERR) ^^^^^
W20160215-13:40:23.444(1)? (STDERR) SyntaxError: Unexpected reserved word`

**Comment by monbro** [comment]
Ah okay, I needed to add https://atmospherejs.com/meteor/ecmascript - maybe you want to add this into the documentation as a requirement or to clarify?

**Comment by aumel** [comment]
I will add info about it in documentation (installation section).

By default, the `ecmascript` package is already installed when you create a new project with Meteor `v1.2.x`.
